---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@main
    with:
      # Single-repo layout: this repo is the HA add-on repository itself.
      repository: home-assistant-addons
      repository_edge: home-assistant-addons
      repository_beta: home-assistant-addons
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
